version: '3.8'
services:

  nutrisync-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - nutrisync-backend-network
  
  nutrisync-backend:
    image: nutrisync-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      NUTRISYNC_ADMINUSER_EMAIL: ${NUTRISYNC_ADMINUSER_EMAIL}
      NUTRISYNC_ADMINUSER_PASSWORD: ${NUTRISYNC_ADMINUSER_PASSWORD}
      NUTRISYNC_ADMINUSER_USERNAME: ${NUTRISYNC_ADMINUSER_USERNAME}
      NUTRISYNC_JWT_ISSUER_SIGNING_KEY: ${NUTRISYNC_JWT_ISSUER_SIGNING_KEY}
      NUTRISYNC_JWT_VALID_AUDIENCE: ${NUTRISYNC_JWT_VALID_AUDIENCE}
      NUTRISYNC_JWT_VALID_ISSUER: ${NUTRISYNC_JWT_VALID_ISSUER}

networks:
  nutrisync-backend-network:
